services:

  ecommerce-api:
    build:
      context: .
      dockerfile: ECommerce.API/Dockerfile
    container_name: ecommerce-api
    ports:
      - "5000:8080"
    depends_on:
      ecommerce-sql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql,1433;Database=ECommerceDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;
      - Redis__Connection=redis:6379

  ecommerce-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sql
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq
    container_name: ecommerce-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build:
      context: .
      dockerfile: ECommerce.Worker/Dockerfile
    container_name: ecommerce-worker
    depends_on:
      - rabbitmq
    restart: always

  ecommerce-outboxworker:
    build:
      context: .
      dockerfile: ECommerce.OutboxWorker/Dockerfile
    container_name: ecommerce-outboxworker
    depends_on:
      ecommerce-api:
        condition: service_started
      ecommerce-sql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql,1433;Database=ECommerceDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;